ings_file_type: csv
trgt_file_type: parquet

local_path: temp_data
dimension_path: dimension

user:
  url: https://github.com/LilyTao123/financial-transaction-data/releases/download/users/output_users.csv
  table_name: user

cards:
  url:  https://github.com/LilyTao123/financial-transaction-data/releases/download/card/cards_data.csv
  table_name: cards

trnsction: 
  url: https://github.com/LilyTao123/financial-transaction-data/releases/download/transaction/transactions_data.zip
  igst_table_name: transactions_data
  table_name: trnsction
