version: 2

sources:
  - name: staging
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    # database: finance-transaction
    schema: "{{ env_var('GCP_BIGQUERY_DATASET') }}" 
    # schema: financial_transaction
    tables:
      - name: user
      - name: cards
      - name: trnsction
      - name: mcc 

models:
  - name: stg_mcc
    description: ""

  - name: stg_trnsction
    description: ""
    columns:
      - name: unique_transaction_id
        data_type: string
        description: ""

      - name: transaction_id
        data_type: int64
        description: ""

      - name: transaction_time
        data_type: string
        description: ""

      - name: transaction_date
        data_type: date
        description: ""

      - name: client_id
        data_type: int64
        description: ""

      - name: card_id
        data_type: int64
        description: ""

      - name: transaction_amount
        data_type: numeric
        description: ""

      - name: use_chip
        data_type: string
        description: ""

      - name: merchant_id
        data_type: int64
        description: ""

      - name: raw_merchant_state
        data_type: string
        description: ""

      - name: merchant_country
        data_type: string
        description: ""

      - name: merchant_state
        data_type: string
        description: ""

      - name: merchant_city
        data_type: string
        description: ""

      - name: zip
        data_type: string
        description: ""

      - name: mcc
        data_type: string
        description: ""

      - name: is_online_transaction
        data_type: boolean
        description: ""

      - name: transaction_status
        data_type: string
        description: ""

      - name: transaction_status_code
        data_type: int64
        description: "if the transaction is successful, it equals to 1 otherwise 0"

      - name: fail_reason
        data_type: string
        description: ""

  - name: stg_cards
    description: ""
    columns:
      - name: card_id
        data_type: int64
        description: ""

      - name: client_id
        data_type: int64
        description: ""

      - name: card_brand
        data_type: string
        description: ""

      - name: card_type
        data_type: string
        description: ""

      - name: card_number
        data_type: string
        description: ""

      - name: card_expired_date
        data_type: date
        description: ""

      - name: is_has_chip
        data_type: boolean
        description: ""

      - name: num_cards_issued
        data_type: int64
        description: ""

      - name: credit_limit
        data_type: numeric
        description: ""

      - name: acct_open_date
        data_type: date
        description: ""

      - name: year_pin_last_changed
        data_type: int64
        description: ""

      - name: is_card_on_dark_web
        data_type: boolean
        description: ""

  - name: stg_user
    description: ""
    columns:
      - name: client_id
        data_type: int64
        description: ""

      - name: current_age
        data_type: int64
        description: ""

      - name: retirement_age
        data_type: int64
        description: ""

      - name: client_birth_year
        data_type: int64
        description: ""

      - name: client_birth_month
        data_type: int64
        description: ""

      - name: gender
        data_type: string
        description: ""

      - name: client_address
        data_type: string
        description: ""

      - name: latitude
        data_type: numeric
        description: ""

      - name: longitude
        data_type: numeric
        description: ""

      - name: city
        data_type: string
        description: ""

      - name: state
        data_type: string
        description: ""

      - name: country
        data_type: string
        description: ""

      - name: per_capita_income
        data_type: numeric
        description: ""

      - name: yearly_income
        data_type: numeric
        description: ""

      - name: if_above_avg_income
        data_type: boolean
        description: ""

      - name: total_debt
        data_type: numeric
        description: ""

      - name: credit_score
        data_type: numeric
        description: ""

      - name: num_credit_cards
        data_type: int64
        description: ""
