name: Airflow CI/CD

on:
  push:
    branches:
      - main  # Runs on push to main branch
  pull_request:
    branches:
      - main  # Runs on PRs to main branch

jobs:
  test-dags:
    name: Test Airflow DAGs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Airflow & Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install apache-airflow
          pip install -r requirements.txt

      - name: Validate DAGs
        run: |
          python -c "from airflow.models import DagBag; dag_bag = DagBag(); assert not dag_bag.import_errors"

  deploy-dags:
    name: Deploy DAGs to Airflow
    runs-on: ubuntu-latest
    needs: test-dags
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy DAGs to Airflow Server
        run: |
          scp -r dags/ my-airflow-server:/opt/airflow/dags/
