name: Airflow CI/CD

on:
  push:
    branches:
      - main  # Runs on push to main branch
  pull_request:
    branches:
      - main  # Runs on PRs to main branch

jobs:
  test-dags:
    name: Test Airflow DAGs
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Airflow & Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --constraint=https://raw.githubusercontent.com/apache/airflow/constraints-2.10.0/constraints-3.11.txt -r airflow-etl/requirements.txt

      - name: Run DAG Tests
        run: |
          pytest airflow-etl/tests/dags/test.py  # Run DAG tests

  deploy-dags:
    name: Deploy DAGs to Airflow
    runs-on: ubuntu-latest
    needs: test-dags
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy DAGs to Airflow Server
        run: |
          scp -r dags/ my-airflow-server:/opt/airflow/dags/
